### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activateItemForURI' of undefined

### ISSUE THREAD

**Issue by pdux** [newinnovations/remote-edit-ni#30]
Steps to reproduce

1. open ATOM
2. Packages -> Remote Edit -> Browse Hosts
3. Connect by sftp to any host with RSA key 
4. try to open any txt file 

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'activateItemForURI' of undefined

```
At /Users/abc/.atom/packages/remote-edit-ni/lib/view/tree-view.coffee:275

TypeError: Cannot read property 'activateItemForURI' of undefined
    at /packages/remote-edit-ni/lib/view/tree-view.coffee:275:20)
    at HTMLDivElement.dispatch (/packages/remote-edit-ni/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/remote-edit-ni/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:43 remote-edit:browse (input.hidden-input)
     -3:57.1.0 remote-edit:close-all-connections (atom-pane.pane.active)
     -3:37.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:45.1.0 remote-edit:browse (div.package-detail.panels-item)
```

### Non-Core Packages

```
remote-edit-ni 3.5.1 
```

**Comment by urban-1** [comment]
Hi @pdux 

Can you reproduce this every time? I have tried this on Linux (Ubuntu) with both atom 1.23.3 and 1.29.0 by sshing to localhost (using the default .ssh/id_rsa) and I cannot make it happen?!

I will try again on my work Mac and let you know. It would help if you can confirm the above steps you made and if this happens all the time

In any case, cheers for let us know :)

**Comment by pdux** [comment]
Hi, 
yes I can confirm it still there, I can't edit remotely. 
I've disabled firewall also. 
It happened first time after ATOM update.

**Comment by newinnovations** [comment]
I am not able to reproduce this on my macbook air. It just seems to work.

What is the OS of the host do you log into?

On the mac I have another 'problem', which requires me to login using ssh to some host first. Only then will the ssh agent be available for remote-edit.

**Comment by newinnovations** [comment]
I got this error today. The situation was that the file was not in a tab, but it was shown in the open files list. The exception occurred when I clicked on the filename in the list. Cannot remember closing the file explicitly. Somehow the open file list can get out of sync with reality. Another issue is that the file list is not populated after restarting atom.
