### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by mmmaniva** [newinnovations/remote-edit-ni#34]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.12.6
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.5.1

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:85

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:85:21)
    at InterProcessDataWatcher.module.exports.InterProcessDataWatcher.onDidChange (/packages/remote-edit-ni/lib/model/inter-process-data-watcher.coffee:102:16)
    at HostsView.module.exports.HostsView.initialize (/packages/remote-edit-ni/lib/view/hosts-view.coffee:18:30)
    at /packages/ftp-remote-edit/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/ftp-remote-edit/node_modules/atom-space-pen-views/lib/select-list-view.js:18:51)
    at /packages/remote-edit-ni/lib/view/hosts-view.coffee:11:9)
    at Object.browse (/packages/remote-edit-ni/lib/main.coffee:141:12)
    at /packages/remote-edit-ni/lib/main.coffee:114:67)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -6:16.3.0 tree-view:copy-full-path (span.name.icon.icon-file-text)
     -5:57.3.0 core:backspace (input.hidden-input)
     -5:56 core:paste (input.hidden-input)
     -4:42.6.0 remote-edit:new-host-sftp (div.panels-item)
     -4:32.8.0 remote-edit:browse (div.panels-item)
     -4:21.7.0 remote-ftp:connect (div.panels-item)
     -3:42 remote-edit:close-all-connections (button.btn.icon.enablement.icon-playback-play)
     -3:36.3.0 remote-edit:toggle-files-view (button.btn.icon.enablement.icon-playback-play)
  2x -3:26 remote-edit:new-host-sftp (button.btn.icon.enablement.icon-playback-pause)
     -3:09.8.0 remote-edit:browse (button.btn.icon.enablement.icon-playback-pause)
     -2:14.7.0 core:confirm (input.hidden-input)
     -1:08.8.0 remote-edit:new-sftp-host (button.btn.icon.enablement.icon-playback-pause)
     -1:05.9.0 core:paste (input.hidden-input)
 58x -1:04.0 core:backspace (input.hidden-input)
     -0:47.9.0 core:paste (input.hidden-input)
     -0:20.3.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
ftp-remote-edit 0.12.16 
platformio-ide-terminal 2.8.4 
remote-edit 1.9.0 
remote-edit-ni 3.5.1 
remote-ftp 2.2.0 
remote-sync 4.1.8 
```

**Comment by newinnovations** [comment]
Not sure what is happening here, but it looks like some interaction/incompatibility  with the ftp-remote-edit package.

**Comment by osbjmg** [comment]
I encountered this error on windows10 doing the following:

- used Atom to edit the `remoteEdit.json` file
- forgot the the closing square bracket an the next to last line
- saving the `remoteEdit.json` file with carriage returns and indents
- disabling / enabling the package from settings
- attempting to browse hosts `Alt+R b`

I attempted to fix the .json file by adding the bracket and removing spaces and carriage returns, but I still saw the error after re-opening Atom.

Ultimately I deleted the contents of `remoteEdit.json` and added the host from the remote-edit-ni dialog box, and now the error does not occur.
