### ISSUE TITLE
Uncaught Error: watch $ATOM_HOME/remoteEdit.json ENOSPC

### ISSUE THREAD

**Issue by lendrick** [newinnovations/remote-edit-ni#40]
1. Alt-r b

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: "Red Hat
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.5.1

### Stack Trace

Uncaught Error: watch /home/OSUMC.EDU/kels12/.atom/remoteEdit.json ENOSPC

```
At fs.js:1388

Error: watch /home/OSUMC.EDU/kels12/.atom/remoteEdit.json ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1386:19)
    at Proxy.fs.watch (fs.js:1412:11)
    at InterProcessDataWatcher.module.exports.InterProcessDataWatcher.watcher (/packages/remote-edit-ni/lib/model/inter-process-data-watcher.coffee:25:10)
    at /packages/remote-edit-ni/lib/model/inter-process-data-watcher.coffee:20:10
    at FSReqWrap.oncomplete (fs.js:135:15)
```

### Commands

```
  2x -0:22.6.0 core:backspace (input.hidden-input)
     -0:19.3.0 remote-edit:browse (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
Atom-Syntax-highlighting-for-Sass 0.5.0 
busy-signal 1.4.3 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
pigments 0.40.2 
remote-edit-ni 3.5.1 
sass 0.5.0 
script 3.18.1 
seti-icons 1.5.4 
tool-bar 1.1.10 
```

**Comment by urban-1** [comment]
Hello, it seems that your drive has run out of space - based on [ENOSPC](https://stackoverflow.com/questions/22475849/node-js-what-is-enospc-error-and-how-to-solve). Can you confirm you have write permissions in that folder and enough available space?
