### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sftp' of null

### ISSUE THREAD

**Issue by K-Nick** [newinnovations/remote-edit-ni#44]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'sftp' of null

```
At C:\Users\Administrator\.atom\packages\remote-edit-ni\lib\model\sftp-host.coffee:314

TypeError: Cannot read property 'sftp' of null
    at async.waterfall._this.tmp_sftp (/packages/remote-edit-ni/lib/model/sftp-host.coffee:314:23)
    at fn (/packages/pdf-view/node_modules/async/lib/async.js:746:34)
    at /packages/pdf-view/node_modules/async/lib/async.js:1213:16
    at /packages/pdf-view/node_modules/async/lib/async.js:166:37
    at /packages/pdf-view/node_modules/async/lib/async.js:706:43
    at /packages/pdf-view/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/packages/pdf-view/node_modules/async/lib/async.js:710:44)
    at SftpHost.module.exports.SftpHost.deleteFolderFile (/packages/remote-edit-ni/lib/model/sftp-host.coffee:312:13)
    at atom.confirm.buttons.Yes (/packages/remote-edit-ni/lib/view/files-view.coffee:683:20)
    at ApplicationDelegate.confirm (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:1:711839)
    at AtomEnvironment.confirm (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:1:699337)
    at FilesView.module.exports.FilesView.deleteFolderFile (/packages/remote-edit-ni/lib/view/files-view.coffee:678:12)
    at FilesView.deleteFolderFile (/packages/remote-edit-ni/lib/view/files-view.coffee:1:1)
    at /packages/remote-edit-ni/lib/view/files-view.coffee:549:98)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:350121)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:11:348596)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:1:704807)
    at EventEmitter.t (~/AppData/Local/atom/app-1.36.0/resources/app/static/<embedded>:1:712847)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -2:44.3.0 core:move-up (input.hidden-input)
  2x -2:43.7.0 hostview:delete (input.hidden-input)
     -2:40.2.0 core:confirm (input.hidden-input)
  2x -2:00.5.0 remote-edit:remove-folder-file (span.text-subtle.text-smaller)
     -1:35.4.0 command-palette:toggle (atom-pane.pane)
 25x -0:35.3.0 core:move-down (input.hidden-input)
     -0:33.5.0 core:move-up (input.hidden-input)
 14x -0:33.1.0 core:move-down (input.hidden-input)
     -0:29.1.0 core:move-up (input.hidden-input)
     -0:28.6.0 core:confirm (input.hidden-input)
     -0:28.6.0 remote-edit:close-all-connections (atom-pane.pane)
     -0:25.6.0 command-palette:toggle (atom-pane.pane)
     -0:23.4.0 core:confirm (input.hidden-input)
     -0:23.4.0 remote-edit:browse (atom-pane.pane)
     -0:21.6.0 core:confirm (input.hidden-input)
     -0:17.3.0 remote-edit:remove-folder-file (span.text-subtle.text-smaller)
```

### Non-Core Packages

```
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
file-type-icons 1.3.4 
gcc-make-run 0.2.12 
Hydrogen 2.9.0 
intentions 1.1.5 
kite 0.154.0 
language-latex 1.2.0 
latex 0.50.2 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
pdf-view 0.71.0 
remote-edit-ni 3.5.1 
script 3.18.1 
sync-settings 0.8.6 
```

**Comment by newinnovations** [comment]
Not enough information to dig into this...
