### ISSUE TITLE
Nan version error after Atom's update

### ISSUE THREAD

**Issue by sungho-cho** [newinnovations/remote-edit-ni#47]
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:196:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
../../nan/nan_maybe_43_inl.h:220:17: error: no member named 'CloneElementAt' in 'v8::Array'
  return array->CloneElementAt(GetCurrentContext(), index);
         ~~~~~  ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:38: error: too few arguments to function call, expected 2, have 1
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
         ~~~~~~~~~~~~~~~~~~~~~~      ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:4899:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, bool value);
  ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:40:60: error: expected '(' for function-style cast or type construction
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                          ~~~~~~~~~~~~~~~~~^
../../nan/nan_implementation_12_inl.h:40:62: error: expected expression
  return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                                             ^
In file included from ../src/main.cc:1:
../../nan/nan.h:822:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:93:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/main.cc:1:
../../nan/nan.h:836:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:86:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/main.cc:1:
../../nan/nan.h:850:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:79:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/main.cc:1:
../../nan/nan.h:1463:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:93:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/core.h:35:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/main.cc:1:
../../nan/nan.h:2019:7: error: no viable conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'Local<v8::Name>'
    , getter_
      ^~~~~~~
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:202:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'const v8::Local<v8::Name> &' for 1st argument
class Local {
      ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:202:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'imp::NativeGetter' (aka 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)') to 'v8::Local<v8::Name> &&' for 1st argument
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:206:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value> &)'
  V8_INLINE Local(Local<S> that)
            ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:3211:39: note: passing argument to parameter 'name' here
                          Local<Name> name,
                                      ^
../src/main.cc:10:39: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  bool success = keytar::AddPassword(*String::Utf8Value(info[0]),
                                      ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/main.cc:11:39: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
                                     *String::Utf8Value(info[1]),
                                      ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/main.cc:12:39: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
                                     *String::Utf8Value(info[2]));
                                      ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/main.cc:19:39: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  bool success = keytar::GetPassword(*String::Utf8Value(info[0]),
                                      ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/main.cc:20:39: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
                                     *String::Utf8Value(info[1]),
                                      ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/main.cc:33:42: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  bool success = keytar::DeletePassword(*String::Utf8Value(info[0]),
                                         ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/main.cc:34:42: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
                                        *String::Utf8Value(info[1]));
                                         ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/main.cc:41:40: warning: 'Utf8Value' is deprecated [-Wdeprecated-declarations]
  bool success = keytar::FindPassword(*String::Utf8Value(info[0]), &password);
                                       ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:2819:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:47:
In file included from /Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/src/node.h:54:
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:213:5: error: assigning to 'v8::Context *' from incompatible type 'v8::String *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/sung/.atom/.node-gyp/.node-gyp/iojs-3.1.10/deps/v8/include/v8.h:167:39: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                      ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:2018:7: note: in instantiation of function template specialization 'v8::Local<v8::Context>::Local<v8::String>' requested here
      name
      ^
12 warnings and 7 errors generated.
make: *** [Release/obj.target/keytar/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sung/.atom/packages/remote-edit-ni/node_modules/keytar
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@3.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sung/.atom/.apm/_logs/2019-09-09T00_00_44_352Z-debug.log

**Comment by Solo-Jordan** [comment]
Similar issue happened to me. I had updated my macbook's OS at the same time. A 'brew update' in terminal fixed the issue for me.
