### ISSUE TITLE
Uncaught Error: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by sandhawalia** [newinnovations/remote-edit-ni#49]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.4
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.5.1

### Stack Trace

Uncaught Error: Cannot parse privateKey: Unsupported key format

```
At /Users/hsandha/.atom/packages/remote-edit-ni/node_modules/ssh2/lib/client.js:146

Error: Cannot parse privateKey: Unsupported key format
    at Client.connect (/packages/remote-edit-ni/node_modules/ssh2/lib/client.js:146:13)
    at /packages/remote-edit-ni/lib/model/sftp-host.coffee:166:23
    at fn (/packages/ftp-remote-edit/node_modules/async/lib/async.js:746:34)
    at /packages/ftp-remote-edit/node_modules/async/lib/async.js:1213:16
    at /packages/ftp-remote-edit/node_modules/async/lib/async.js:166:37
    at /packages/ftp-remote-edit/node_modules/async/lib/async.js:706:43
    at /packages/ftp-remote-edit/node_modules/async/lib/async.js:167:37
    at /packages/ftp-remote-edit/node_modules/async/lib/async.js:1209:30
    at /packages/remote-edit-ni/lib/model/sftp-host.coffee:125:17
    at suppressedCallback (fs.js:238:5)
    at FSReqWrap.oncomplete (fs.js:169:20)
```

### Commands

```
     -1:26.4.0 core:cancel (input.hidden-input)
     -1:16.8.0 remote-ftp:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:08.5.0 remote-ftp:connect (div.tool-panel.tree-view)
     -1:05.5.0 core:confirm (input.hidden-input)
     -0:56.2.0 remote-edit:browse (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-ftp-editor 0.5.0 
autocomplete-python 1.16.0 
ftp-remote-edit 0.17.4 
goto-definition 1.3.4 
hyperclick 0.1.5 
linter 2.3.1 
linter-pycodestyle 2.1.3 
linter-pylama 0.10.1 
linter-pylint 2.1.1 
linter-python 3.1.2 
linter-python-pep257 0.0.1 
linter-python-pep8 0.2.0 
linter-ui-default 1.8.0 
pretty-json 2.1.2 
python-autopep8 0.1.3 
python-indent 1.2.3 
python-tools 0.6.9 
remote-edit-ni 3.5.1 
remote-ftp 2.2.2 
stop-cursor-blinking 1.0.1 
```

**Comment by ali3nnn** [comment]
Same problem here

**Comment by urban-1** [comment]
This error seems to be coming from ssh2 lib/implementation. Have you tried changing your private keys with `ssh-keygen`? 

Related post: https://stackoverflow.com/a/53995132/3727050

**Comment by newinnovations** [comment]
What is the type of private key that you are using?

**Comment by surak** [comment]
rsa 4096 bits

**Comment by surak** [comment]
or ecdsa 521 bits.

**Comment by surak** [comment]
also fails with ed25519

**Comment by surak** [comment]
> This error seems to be coming from ssh2 lib/implementation. Have you tried changing your private keys with `ssh-keygen`?

Cannot. RSA is too old and not accepted anymore in many places.
