### ISSUE TITLE
Uncaught Error: PPK MAC mismatch

### ISSUE THREAD

**Issue by Qing-LAB** [newinnovations/remote-edit-ni#52]
[Enter steps to reproduce:]

1. added new host to use private key to connect. this private key file worked fine on PuTTY
2. connect to server, and get this error

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.6.0

### Stack Trace

Uncaught Error: PPK MAC mismatch

```
At C:\Users\quanq\.atom\packages\remote-edit-ni\node_modules\ssh2-streams\lib\utils.js:137

Error: PPK MAC mismatch
    at decryptKey (/packages/remote-edit-ni/node_modules/ssh2-streams/lib/utils.js:137:15)
    at Client.connect (/packages/remote-edit-ni/node_modules/ssh2/lib/client.js:152:7)
    at /packages/remote-edit-ni/lib/model/sftp-host.coffee:166:23
    at fn (/packages/remote-edit-ni/node_modules/async/lib/async.js:746:34)
    at /packages/remote-edit-ni/node_modules/async/lib/async.js:1213:16
    at /packages/remote-edit-ni/node_modules/async/lib/async.js:166:37
    at /packages/remote-edit-ni/node_modules/async/lib/async.js:706:43
    at /packages/remote-edit-ni/node_modules/async/lib/async.js:167:37
    at /packages/remote-edit-ni/node_modules/async/lib/async.js:1209:30
    at /packages/remote-edit-ni/lib/model/sftp-host.coffee:125:17
    at suppressedCallback (fs.js:209:5)
    at FSReqCallback.oncomplete (fs.js:150:20)
```

### Commands

```
     -0:08.4.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
Hydrogen 2.14.2 
language-igor 0.1.1 
remote-edit-ni 3.6.0 
```

**Comment by Qing-LAB** [comment]
Sorry. The reason for the error was that the pass-phrase was incorrect with a typo.
The connection was opened correctly with the right pass-phrase.
issue closed.
