### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, watch '~/.atom/remoteEdit.json'

### ISSUE THREAD

**Issue by engespresso** [newinnovations/remote-edit-ni#58]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: linux 5.4.0-74-generic
**Thrown From**: [remote-edit-ni](https://github.com/newinnovations/remote-edit-ni) package 3.6.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, watch '/home/kalev/.atom/remoteEdit.json'

```
At internal/fs/watchers.js:173

Error: ENOENT: no such file or directory, watch '/home/kalev/.atom/remoteEdit.json'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Proxy.watch (fs.js:1329:11)
    at InterProcessDataWatcher.module.exports.InterProcessDataWatcher.watcher (/packages/remote-edit-ni/lib/model/inter-process-data-watcher.coffee:25:10)
    at /packages/remote-edit-ni/lib/model/inter-process-data-watcher.coffee:20:10
    at FSReqCallback.oncomplete (fs.js:146:23)
```

### Commands

```
     -0:54.5.0 remote-edit:new-sftp-host (atom-pane.pane.active)
 15x -0:39.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
remote-edit-ni 3.6.0 
```

**Comment by aendi123** [comment]
Solved it by running these commands in the shell of the host with atom installed:
```
cd
mkdir .atom
touch .atom/remoteEdit.json
```
